import { RequestStatusEnum } from './enums';
import { BaseModel } from './base-model';
import { LenderModel } from './lender-model';
import { LoanTypeModel } from './loan-type-model';
import { UserModel } from './user-model';
import { StateModel } from './state-model';
import { CountryModel } from './country-model';

export class LoanModel extends BaseModel {
  public userId: number;
  public user: UserModel;
  public loanTypeId: number;
  public loanType: LoanTypeModel;
  public lenderId: number;
  public lender: LenderModel;
  public loanAmount: number;
  public loanPurpose: string;
  public loanTenor: number;
  public paybackFrequency: string;
  public interestRate: number;
  public moratoriumPeriod: number;
  public bankName: string;
  public bankCode: string;
  public accountNumber: string;
  public accountName: string;
  public taxID: string;
  public bvn: string;
  public bvnIsValid: boolean;
  public bvnValidationError: string;
  public currencyCode: string;
  public referenceNumber: string;
  public isEligible: boolean;
  public retryCount: number;
  public requestDate: Date;
  public requestChannel: string;
  public brokerCode: string;
  public loanStatus: string | RequestStatusEnum;
  public loanProcessor: string;
  public overdueBalance: number;
  public residenceAddress: string;
  public residenceCity: string;
  public residenceStateId: number;
  public residenceState: StateModel;
  public residenceCountryId: number;
  public residenceCountry: CountryModel;
  public monthySalaryOrTurnover: number;
  public isBusinessRegistered: boolean;
  public businessRegNumber: string;
  public employerOrBusinessName: string;
  public employerOrBusinessAddress: string;
  public employerOrBusinessCity: string;
  public employerOrBusinessStateId: number;
  public employerOrBusinessState: StateModel;
  public employerOrBusinessCountryId: number;
  public employerOrBusinessCountry: CountryModel;
}
